#!/bin/bash
#  this script performs a subset of calculations for the Hands-On PAW course
#   
#  Here: magnetism
#
#  It relies on a data structure in the ROOT directory specified below
#  with a SRC directory containing all input files required, and a
#  SANDBOX directory where the calculations are performed, and where
#  the resulting files are kept.
#
function error {
  if [[ $1 != 0 ]] ; then 
    error "in $0:$THIS: $2"
    exit $IERR
  fi
  IERR=$(echo "$IERR+1" |bc -l)
}

ROOT='/Users/ptpb/Tree/PhiSX/Praktikum/Calculations'
SRC=$ROOT/Container
SANDBOX=$ROOT/Sandbox
IERR=1
cd $SANDBOX; error $? "not in sandbox"
#==================================================================
#== chapter Convergence tests
#==================================================================
#==  plane wave convergence of iron (wave functions)
PREV=fe_1
THIS=fe_2
# DIR=TestEPW
# if [[ ! -d $DIR ]] ; then mkdir $DIR ; fi
# cd $DIR                           ; error $? "cd $DIR failed"
# cp ../$PREV.rstrt $THIS.rstrt       ; error $? "cp ../$PREV.rstrt failed"
# cp $SRC/$THIS.cntl $THIS.cntl     ; error $? "copy cntl failed"
# cp $SRC/$PREV.strc $THIS.strc     ; error $? "copy strc failed"
# paw_scan -r "EPW 20 25 30 35 40 50 60 70" -w fast -- ./${THIS}
# if [[ -e etot.dat ]] ; then rm etot.dat ; fi
# for X in ``20 25 30 35 40 50 60 70''; do 
#   echo "$X $(paw_get -nw etot -- ${THIS}_${X}/${THIS}_${X})" >> etot.dat
# done
# cd $SANDBOX
#
#==  plane wave convergence of iron (charge density)
PREV=fe_1
THIS=fe_3
DIR=TestCDUAL
if [[ ! -d $DIR ]] ; then mkdir $DIR ; fi
cd $DIR                             ; error $? "cd $DIR failed"
cp ../$PREV.rstrt $THIS.rstrt       ; error $? "cp ../$PREV.rstrt failed"
cp $SRC/$THIS.cntl $THIS.cntl    ; error $? "copy cntl failed"
cp $SRC/$PREV.strc $THIS.strc    ; error $? "copy strc failed"
paw_scan -r "CDUAL 2 3 4 5 6" -w fast -- ./${THIS}
if [[ -e etot.dat ]] ; then rm etot.dat ; fi
for X in ``2 3 4 5 6''; do 
  echo "$X $(paw_get -nw etot -- ${THIS}_${X}/${THIS}_${X})" >> etot.dat
done
cd $SANDBOX
