#!/bin/bash
#  this script performs a subset of calculations for the Hands-On PAW course
#   
#  Here: Malonaldehyde
#
#  It relies on a data structure in the ROOT directory specified below
#  with a SRC directory containing all input files required, and a
#  SANDBOX directory where the calculations are performed, and where
#  the resulting files are kept.
#
function error {
  if [[ $1 != 0 ]] ; then 
    error "in $0:$THIS: $2"
    exit $IERR
  fi
  IERR=$(echo "$IERR+1" |bc -l)
}

ROOT='/Users/ptpb/Tree/PhiSX/Praktikum/Calculations'
SRC=$ROOT/Container
SANDBOX=$ROOT/Sandbox
IERR=1
cd $SANDBOX; error $? "not in sandbox"
#==================================================================
#== chapter 4. Malonaldehyde
#==================================================================
#
#==  optimization of the electronic structure =====================
THIS=c3o2h4_1
cp $SRC/$THIS.cntl $THIS.cntl   ; error $? "copy cntl failed"
cp $SRC/$THIS.strc $THIS.strc   ; error $? "copy strc failed"
#if [[ -e  $THIS.prot ]] ; then rm $THIS.prot ; fi
#paw_fast.x $THIS.cntl 1>out 2>&1; error $? "paw_fast.x failed"
paw_show -ec $THIS $THIS.show_out; error $? "paw_show.x failed"
##### use gracebat?
#
#
#== optimize atomic structure of malonaldehyde=====================
PREV=$THIS
THIS=c3o2h4_2
# cp $PREV.rstrt $THIS.rstrt       ; error $? "copy rstrt failed"
# cp $PREV.strc  $THIS.strc        ; error $? "copy strc failed"
# cp $SRC/$THIS.cntl $THIS.cntl    ; error $? "copy cntl failed"
# if [[ -e  $THIS.prot ]] ; then rm $THIS.prot ; fi
# paw_fast.x $THIS.cntl 1>out 2>&1 ; error $? "paw_fast.x failed"
# paw_show -ec $THIS $THIS.show_out; error $? "paw_show.x failed"
# paw_strc.x -m $THIS 1>out 2>&1   ; error $? "paw_strc.x failed"
#
#
#== continue optimization with friction between zero and one.
PREV=$THIS
THIS=c3o2h4_2a
# cp $PREV.rstrt $THIS.rstrt       ; error $? "copy rstrt failed"
# cp $PREV.strc  $THIS.strc        ; error $? "copy strc failed"
# cp $PREV.prot  $THIS.prot        ; error $? "copy strc failed"
# cp $SRC/$THIS.cntl $THIS.cntl    ; error $? "copy cntl failed"
# paw_fast.x $THIS.cntl 1>out 2>&1 ; error $? "paw_fast.x failed"
# paw_show -ec $THIS $THIS.show_out; error $? "paw_show.x failed"
#
#== convergence ==============================================-----
PREV=$THIS
THIS=c3o2h4_3
# cp $PREV.rstrt $THIS.rstrt       ; error $? "copy rstrt failed"
# cp $PREV.strc  $THIS.strc        ; error $? "copy strc failed"
# cp $SRC/$THIS.cntl $THIS.cntl    ; error $? "copy cntl failed"
# if [[ -e  $THIS.prot ]] ; then rm $THIS.prot ; fi
# paw_fast.x $THIS.cntl 1>out 2>&1 ; error $? "paw_fast.x failed"
# paw_show -ec $THIS $THIS.show_out; error $? "paw_show.x failed"
#
#==density of states===========================================
PREV=$THIS
THIS=c3o2h4_4a
cp $PREV.pdos $THIS.pdos          ; error $? "copy pdos failed"
cp $SRC/$THIS.dcntl $THIS.dcntl   ; error $? "copy dcntl failed"
if [[ ! -d Dos_M ]] ; then mkdir Dos_M ; fi
paw_dos.x $THIS.dcntl             ; error $? "paw_dos.x failed"
cp $SRC/$THIS.dpcntl $THIS.dpcntl ; error $? "copy dpcntl failed"
paw_dosplot.x $THIS.dpcntl        ; error $? "paw_dosplot.x failed"
gracebat -nosafe -hdevice EPS -batch $THIS.bat -hardcopy -printfile $THIS.eps
                                  error $? "gracebat failed"
#
#==density of states===========================================
PREV=$THIS
THIS=c3o2h4_4b
cp $PREV.pdos $THIS.pdos          ; error $? "copy pdos failed"
cp $SRC/$THIS.dcntl $THIS.dcntl   ; error $? "copy dcntl failed"
if [[ ! -d Dos_M ]] ; then mkdir Dos_M ; fi
paw_dos.x $THIS.dcntl             ; error $? "paw_dos.x failed"
cp $SRC/$THIS.dpcntl $THIS.dpcntl ; error $? "copy dpcntl failed"
paw_dosplot.x $THIS.dpcntl        ; error $? "paw_dosplot.x failed"
gracebat -nosafe -hdevice EPS -batch $THIS.bat -hardcopy -printfile $THIS.eps
                                  error $? "gracebat failed"
#
#==density of states===========================================
# PREV=$THIS
# THIS=c3o2h4_4
# cp $PREV.pdos $THIS.pdos          ; error $? "copy pdos failed"
# cp $SRC/$THIS.dcntl $THIS.dcntl   ; error $? "copy dcntl failed"
# if [[ ! -d Dos_B ]] ; then mkdir Dos_B ; fi
# paw_dos.x $THIS.dcntl             ; error $? "paw_dos.x failed"
# cp $SRC/$THIS.dpcntl $THIS.dpcntl ; error $? "copy dpcntl failed"
# paw_dosplot.x $THIS.dpcntl        ; error $? "paw_dosplot.x failed"
#
#==wave functions==============================================
# PREV=c3o2h4_3
# THIS=c3o2h4_5
# cp $PREV.rstrt $THIS.rstrt       ; error $? "copy rstrt failed"
# cp $PREV.strc $THIS.strc         ; error $? "copy strc failed"
# cp $SRC/$THIS.cntl $THIS.cntl    ; error $? "copy cntl failed"
# if [[ -e  $THIS.prot ]] ; then rm $THIS.prot ; fi
# paw_fast.x $THIS.cntl 1>out 2>&1 ; error $? "paw_fast.x failed"
# paw_show -ec $THIS $THIS.show_out; error $? "paw_show.x failed"
#
#==================================================================
#== chapter 5. AIMD with Malonaldehyde
#==================================================================
#==molecular dynanics==============================================

